version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Test
          command: yarn test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
        name: Install Heroku
        command: heroku/install
      - run:
        name: Deploy
        command: heroku/deploy-via-git
# workflows:
#   heroku_deploy:
#     jobs:
#       - deploy